server: "172.20.14.119:8001"
topic:
  main: "events-in"
  retry: "events-retry"
  dlq: "events-dlq"
  out: "events-out"
logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %20.30logger{36} - %msg%n"
